name: Théo<span class="short">dore</span> <span class="name">Biadala</span>
title: Théodore Biadala
markdown: kramdown
highlighter: rouge
timezone: Europe/Paris
permalink: /:year/:title.html
domain: read.theodoreb.net
